### ISSUE TITLE
Todo: Structural/editorial

### ISSUE THREAD

**Issue by kallewesterling** [DHRI-Curriculum/mapping#12]
All of the following todos come from [`lessons.md`](https://github.com/DHRI-Curriculum/mapping/edit/v2.0-olivia-edits/lessons.md) and should be visible as HTML comments in that file.

## Lesson: `Introduction to Mapping`
- [x] add "map shapes" to glossary... linked to shapefile and raster data perhaps
- [x] add "feature" and "attribute" to the glossary (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))
- [x] add "raster data" to glossary (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))

## Lesson: `Ethics of mapping`
- [x] perhaps split up this section, using subheaders into 2-3 subsections. The way it reads now feels a bit overpowering

## Lesson: `Making an Interactive Map`
- [x] add a link to shapefile from NYC Open Data
- [x] First time shapefile is mentioned, should be added to glossary (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))
- [x] what does it mean that you have downloaded the spreadsheet here? Is it one of the datasets in the frontmatter? If so, perhaps we should link to it here.

## Lesson: `Combining Data Through a Spatial Join`
- [x] explain what is a polygon layer + add "polygon layer" to glossary (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))
- [x] do we need to clarify what mappable coordinates are, i.e. I presume lat/long? Perhaps another term to add to glossary? (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))
- [x] add an explanation here of what "resolution" means + add "resolution" to glossary? (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))

## Lesson: `Performing a Spatial Join`
- [x] build a file for installation instructions for QGIS (add to directory [`guides`](https://github.com/DHRI-Curriculum/install/tree/v2.0/guides)) + add link here
- [x] add link to "CSV" from glossary (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))
- [x] A little unclear with what it means here that a "CSV file is not mappable" - if it has lat-long coordinates in two separate (or even a single) column, you'd be able to map it, no?
- [x] Add a screenshot of what the shapefile adding to QGIS looks like perhaps?
- [x] Add a screenshot here perhaps of what the attribute table looks like?
- [x] add link to "data type" from glossary (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))

## Lesson: `Importing Data to ArcGIS Online`
- [x] add transitional short paragraph here about ArcGIS, reminding the learner what the difference is (and that there is a difference) between QGIS and ArcGIS

## Lesson: `Changing the Map Style`
- [x] new term for the glossary: cloropleth (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))
- [x] Should we add "color ramp" as a glossary term? (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))
- [x] add image here that does not show the popup but only the finished styled map?

## Lesson: `Importing CSV file and Geocoding Addresses`
- [x] add link to "cloropleth" from glossary to this lesson (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))
- [x] add new term to glossary: geocoding (directory [`term list`](https://github.com/DHRI-Curriculum/glossary/tree/v2.0/terms))

## Lesson: `Formatting the Legend`
- [x] We need a short intro to what the legend is here, I think

**Comment by kallewesterling** [comment]
For reference, all the edits can be seen in the following comparison:
https://github.com/DHRI-Curriculum/mapping/compare/pre-kalle-edits...DHRI-Curriculum:kalle-edit-round1
